### ISSUE TITLE
Same provide name for instances

### ISSUE THREAD

**Issue by luckyraul** [chartbeat-labs/puppet-varnish#15]
Varnish::Instance[instance1]/Service[varnish-instance1]/enable) change from false to true failed: Execution of '/usr/sbin/update-rc.d varnish-instance1 defaults' returned 1: update-rc.d: using dependency based boot sequencing
Varnish::Instance[instance1]/Service[varnish-instance1]/enable) insserv: script varnish-instance1: service varnish already provided!

fix in #16

**Comment by butlern** [comment]
@luckyraul Can you send more info of your test setup? Like the puppet manifest, system info. I cannot duplicate this problem on ubuntu 12.04 with the following:

```puppet
varnish::instance { 'instance1' : }
```

**Comment by luckyraul** [comment]
On Debian wheezy

**Comment by butlern** [comment]
ah, thanks! Looks good to me, will merge it in.

**Comment by luckyraul** [comment]
please also release to puppet forge

**Comment by hpkeiler** [comment]
Hi Chartbeat people,

I was an intern in Fall 2013 and I still get e-mails on this thread from
time-to-time. I tried to unsubscribe a few times, but have been
unsuccessful. It doesn't bother me at all-- but just giving you a heads up
here in case more nefarious people (or people who actually know what  a
puppet-varnish is and no longer are at Chartbeat) are on this thread.

Hope you all are doing well!

Thanks,
Hannah Keiler

**Comment by butlern** [comment]
@luckyraul we are in the process of working out how best to release our modules to the forge. But until we do you'll have to use the git ref with librarian-puppet.

**Comment by butlern** [comment]
@hpkeiler you just need to visit the repo and click Unwatch. If you have further questions, open up a new issue please!
